#!/usr/bin/env python
# -*- coding: UTF8 -*-
#
#   run-devserver.py - Run the Flask development server for Muigi Web 
#
#   AUTHOR: Douglas Watson <douglas@watsons.ch>
#
#   DATE: started on 16 August 2011
#
#   LICENSE: GNU GPL
#
#################################################

import sys
from optparse import OptionParser
from muigi.web import app
from muigi import __version__

"""
run_devserver.py

Starts the Flask development server in debug mode.

For development ONLY. For production, use the CherryPy server.
"""

if __name__ == '__main__':

    HOST = '0.0.0.0'
    PORT = 5000

    parser = OptionParser(version=__version__)
    parser.add_option('-p', '--port', action="store", type="string", 
            dest="port", help="Port number for server to listen on")
    parser.add_option('-H', '--host', action="store", type="int", 
            dest="host", help="Host name to bind port to")

    (options, args) = parser.parse_args()
    
    if options.port: PORT = int(options.port)
    if options.host: HOST = options.host

    app.scheduler.start()
    app.run(debug=True, host=HOST, port=PORT)
    app.scheduler.stop()
